name: CRISPR-transmission
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.12.4
  - bzip2>=1.0.8
  - pandas>=2.2.2
  - minced>=0.4.2
  - piler-cr>=1.06


# Package versions at the time of writing this file
# python                         3.12.4
# bzip2                          1.0.8
# pandas                         2.2.2
# minced                         0.4.2
# piler-cr                       1.06

# ipykernel                      6.29.4
# numpy                          2.0.0
# matplotlib                     3.8.4
# scipy                          1.14.0
# scikit-learn                   1.5.0