name: CRISPRDetect
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl-parallel-forkmanager=2.02
  - clustalw=2.1
  - emboss=6.6.0
  - viennarna=2.6.4
  - cd-hit=4.8.1
  - blast=2.15
  - hmmer=3.4
  # - simple-term-menu>=1.6.4
variables:
  # Add the path to the CRISPRDetect3 folder to the PATH variable in the activate.sh script
  # export PATH="/FULL_PATH_TO_CRISPRDETECT3:$PATH"
  # Remove the path to the CRISPRDetect3 folder from the PATH variable in the deactivate.sh script
  # export PATH=$(echo $PATH | sed -e 's@/FULL_PATH_TO_CRISPRDETECT3:@@g')


