name: CRISPRDetect
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl-parallel-forkmanager=2.02
  - clustalw=2.1
  - emboss=6.6.0
  - viennarna=2.6.4
  - cd-hit=4.8.1
  - blast=2.15
  - hmmer=3.4
  # - simple-term-menu>=1.6.4
  # - pandas>= 2.2.2


# Add the path to the CRISPRDetect3 folder to the PATH variable in the activate.sh script and remove it in the deactivate.sh script
#   mkdir -p ${CONDA_PREFIX}/etc/conda/activate.d
#   mkdir -p ${CONDA_PREFIX}/etc/conda/deactivate.d
#   cat << EOF > ${CONDA_PREFIX}/etc/conda/activate.d/env_vars.sh
#   #!/bin/sh
#   export PATH="FULL/PATH/TO/CRISPRDETECT/DIR:$PATH"
#   EOF
#   cat << EOF > ${CONDA_PREFIX}/etc/conda/deactivate.d/env_vars.sh
#   #!/bin/sh
#   PATH="$(echo "${PATH}" | tr ':' '\n' | grep -v -x -F 'FULL/PATH/TO/CRISPRDETECT/DIR' | tr '\n' ':')" 
#   PATH="${PATH%:}"
#   export PATH
#   EOF

