name: CRISPRDetect
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl-parallel-forkmanager=2.02
  - clustalw=2.1
  - emboss=6.6.0
  - viennarna=2.6.4
  - cd-hit=4.8.1
  - blast=2.15
  - hmmer=3.4



