name: CRISPRDetect
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl-parallel-forkmanager=2.02
  - clustalw=2.1
  - emboss=6.6.0
  - viennarna=2.6.4
  - cd-hit=4.8.1
  - blast=2.15
  - hmmer=3.4
variables:
  # write the path to the CRISPRDetect_3.0 folder in your system
  PATH: "/home/isacco.cenacchi/data/tools/CRISPRDetect_3.0:$PATH" 


