package:
  name: "crisprtools"
  version: "0.1.0"

source:
  path: ..

build:
  script: python -m pip install .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

about:
  home: "https://github.com/isacchetto/CRISPR-spacer-based-Human-microbiome-transmission-analysis"
  license: "MIT"
  license_file: "LICENSE"
  summary: "A toolset for CRISPR analysis."
  description: |
    CRISPRtools is a Python package for simplifying CRISPR-related analysis.

extra:
  recipe-maintainers:
    - isacchetto
